package(default_visibility = ["//visibility:public"])

filegroup(
    name = "dats",
    srcs = glob(["*.dat"]),
)

filegroup(
    name = "txts",
    srcs = glob(["*.txt"]),
)

filegroup(
    name = "binary",
    srcs = glob(["*.ogg"]),
)
